"""add id and site name

Revision ID: 73bdc21caa16
Revises: 575b853b004c
Create Date: 2023-01-10 17:25:54.066260

"""
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "73bdc21caa16"
down_revision = "575b853b004c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prescription", sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False, primary_key=True))
    op.add_column(
        "prescription", sa.Column("site_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False, primary_key=True)
    )
    op.drop_column("prescription", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prescription", sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column("prescription", "site_name")
    op.drop_column("prescription", "user_id")
    # ### end Alembic commands ###
