"""add query & fragment url fields

Revision ID: 7d4e539803ae
Revises: 792137e0de98
Create Date: 2023-05-30 18:07:29.910808

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d4e539803ae"
down_revision = "792137e0de98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("page_urlfragment", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("event", sa.Column("page_urlquery", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("event", sa.Column("refr_urlfragment", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("event", sa.Column("refr_urlquery", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "refr_urlquery")
    op.drop_column("event", "refr_urlfragment")
    op.drop_column("event", "page_urlquery")
    op.drop_column("event", "page_urlfragment")
    # ### end Alembic commands ###
