"""add page_url and page_urlhost

Revision ID: d79e4cdec772
Revises: 7d4e539803ae
Create Date: 2023-06-07 16:56:45.849955

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "d79e4cdec772"
down_revision = "7d4e539803ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("page_url", sa.String(), nullable=True))
    op.add_column("event", sa.Column("page_urlhost", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "page_urlhost")
    op.drop_column("event", "page_url")
    # ### end Alembic commands ###
